-- MySQL Script generated by MySQL Workbench
-- Tue May 20 09:01:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Banco_Bomba` DEFAULT CHARACTER SET utf8 ;
USE `Banco_Bomba` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bomba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco_Bomba`.`Bomba` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Vazao` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Torneira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco_Bomba`.`Torneira` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Torneira` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco_Bomba`.`Caixa` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Capacidade` INT NULL,
  `Sensor_SUP` TINYINT NOT NULL,
  `Sensor_INF` TINYINT NOT NULL,
  `Bomba_ID` INT NOT NULL,
  `Ind_Caixa` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Caixa_Bomba_idx` (`Bomba_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Caixa_Bomba`
    FOREIGN KEY (`Bomba_ID`)
    REFERENCES `Banco_Bomba`.`Bomba` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco_Bomba`.`Reservatorio` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Ind_Reservatorio` VARCHAR(255) NULL,
  `Capacidade` INT NOT NULL,
  `Sensor_SUP` TINYINT NOT NULL,
  `Sensor_INF` TINYINT NOT NULL,
  `Torneira_ID` INT NOT NULL,
  `Caixa_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idReservatorio_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Reservatorio_Torneira1_idx` (`Torneira_ID` ASC) VISIBLE,
  INDEX `fk_Reservatorio_Caixa1_idx` (`Caixa_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Reservatorio_Torneira1`
    FOREIGN KEY (`Torneira_ID`)
    REFERENCES `Banco_Bomba`.`Torneira` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservatorio_Caixa1`
    FOREIGN KEY (`Caixa_ID`)
    REFERENCES `Banco_Bomba`.`Caixa` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Periodo_Funcionamento_Torneira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco_Bomba`.`Periodo_Funcionamento_Torneira` (
  `ID` INT NOT NULL,
  `Data_Hora_Inicio` DATETIME NOT NULL,
  `Data_Hora_Fim` DATETIME NOT NULL,
  `Torneira_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Periodo_Funcionamento_Torneira1_idx` (`Torneira_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Periodo_Funcionamento_Torneira1`
    FOREIGN KEY (`Torneira_ID`)
    REFERENCES `Banco_Bomba`.`Torneira` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Periodo_Funcionamento_Bomba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco_Bomba`.`Periodo_Funcionamento_Bomba` (
  `ID` INT NOT NULL,
  `Data_Hora_Inicio` DATETIME NOT NULL,
  `Data_Hora_Fim` DATETIME NOT NULL,
  `Bomba_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Periodo_Funcionamento_Bomba_Bomba1_idx` (`Bomba_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Periodo_Funcionamento_Bomba_Bomba1`
    FOREIGN KEY (`Bomba_ID`)
    REFERENCES `Banco_Bomba`.`Bomba` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Media_Temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banco_Bomba`.`Media_Temp` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Media_Fun_Bomba` INT NOT NULL,
  `Media_Fun_Torneira` INT NOT NULL,
  `Periodo_Funcionamento_Bomba_ID` INT NOT NULL,
  `Periodo_Funcionamento_Torneira_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Media_Temp_Periodo_Funcionamento_Bomba1_idx` (`Periodo_Funcionamento_Bomba_ID` ASC) VISIBLE,
  INDEX `fk_Media_Temp_Periodo_Funcionamento_Torneira1_idx` (`Periodo_Funcionamento_Torneira_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Media_Temp_Periodo_Funcionamento_Bomba1`
    FOREIGN KEY (`Periodo_Funcionamento_Bomba_ID`)
    REFERENCES `Banco_Bomba`.`Periodo_Funcionamento_Bomba` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Media_Temp_Periodo_Funcionamento_Torneira1`
    FOREIGN KEY (`Periodo_Funcionamento_Torneira_ID`)
    REFERENCES `Banco_Bomba`.`Periodo_Funcionamento_Torneira` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
